### ISSUE TITLE
Encoding issues in RSS feed

### ISSUE THREAD

**Issue by wezm** [myfreeweb/sweetroll2#1]
Since your announcement post that you’d launched sweetrool2 your posts have been appear semi garbled in my feed reader, presumably due to an issue with reported versus actual text encoding. 

![8FE9C752-A596-482A-B6D2-521A75A368ED](https://user-images.githubusercontent.com/21787/65647022-c2ee6980-e02f-11e9-9aec-43d383f54357.png)

I’m using Reeder, syncing to Feedbin. The issue appears in the official Feedbin app too:

![02FAAA81-649C-452B-A46A-814897A6EC70](https://user-images.githubusercontent.com/21787/65647076-0517ab00-e030-11e9-8dae-6cdaf37e125b.png)

**Comment by myfreeweb** [comment]
Should be fine now. granary was confused about the encoding because I didn't return it in the http header. Well, I did, in the dynamic application, but h2o did not for static files :D
